# fly.toml app configuration file generated for rodiger-io-lively-sunset-9275 on 2024-11-16T18:32:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rodiger-io-lively-sunset-9275'
primary_region = 'ewr'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
